### PR TITLE
Implementing Deployment Pipeline for Beta and Production Servers

### PR DESCRIPTION
**Pull request by chinathaip**
## PR Type:
Enhancement

___
## PR Description:
This PR enhances the deployment pipeline to support both beta and production servers. It introduces a matrix strategy in the GitHub Actions workflow to run the pipeline twice, once for each environment. The environment-specific configurations like HOST, USERNAME, PASSWORD are picked up by the `environment: ${{ matrix.environment }}` command. Depending on the environment, the appropriate start script (`./start_dev.sh` for beta and `./start_prod.sh` for production) is executed. Additionally, a test deployment configuration step is added to ensure the correct environment is configured.

___
## PR Main Files Walkthrough:
<details> <summary>files:</summary>

`.github/workflows/deploy-vm.yaml`: The GitHub Actions workflow file has been significantly updated. A matrix strategy has been introduced to handle both beta and production environments. An environment variable is set based on the matrix environment. A new step to test deployment configurations has been added. The script in the "Deploy new changes via SSH" step has been updated to execute the appropriate start script based on the environment.
</details>

### CODE REVIEW

**Comment by Lxkas** [comment]
@CodiumAI-Agent /review

**Comment by Lxkas** [comment]
I agree with the AI, have it send to webhook on failure :3

**Comment by Lxkas** [comment]
Preparing answer...

**Comment by Lxkas** [comment]
Question: does this pr have any typos or inconsistensies?

Answer:
The PR appears to be free from any typos or inconsistencies. The changes made are consistent with the PR description. The deployment pipeline is now configured to run for both 'beta' and 'production' environments, with environment-specific scripts (`./start_dev.sh` for beta and `./start_prod.sh` for production). The environment is picked up by the `environment: ${{ matrix.environment }}` line, which is taken from the matrix configuration. 

The addition of a test deployment configuration step is also a good practice to ensure the correct environment is configured before proceeding with the deployment. 

The code is well-structured and follows the correct syntax for a GitHub Actions workflow file. 

Overall, the PR is well-written and doesn't contain any noticeable typos or inconsistencies.

**Comment by chinathaip** [comment]
This AI knows it won't last long here if it gives bad comments for my work

**Comment by Lxkas** [comment]
> This AI knows it won't last long here if it gives bad comments for my work

I'm using it locally now, u can't stop it :3 It'll comment through my account!

**Review by Lxkas — APPROVED** [review]

**Comment by Lxkas** [comment]
Preparing PR description...

**Pull request merged**
