### PR TITLE
Export HAProxy metrics and create Grafana dashboard + Remove stop emitting unused s3 metrics

### PR DESCRIPTION
**Pull request by chinathaip**
This PR:
- Moves all related files from `/prometheus` to `/monitoring`
- Export HAProxy metrics with built-in HAProxy-Prometheus Exporter
- Deploy Grafana with default prometheus datasource and HAProxy dashboard on container start up
    - https://grafana-beta.stamford.dev
- **BONUS:** remove unused s3 metrics that takes up a lot of storage on VM

### CODE REVIEW

**Comment by Reonowo** [comment]
@CodiumAI-Agent /review

**Comment by Lxkas** [comment]
@CodiumAI-Agent /ask Are the any inconsistencies, typos, or any oversights in the PR?

**Comment by chinathaip** [comment]
> In the monitoring/docker-compose.yaml file, the grafana service is running with user "0". This is the root user, which might not be the best practice from a security perspective. If Grafana doesn't need root privileges to run, consider using a non-root user.

Tried without it, stuck with insufficient permission to bind `/var/lib/grafana` and make data inside persistent

> In the monitoring/conf/alertmanager.yml file, the url for the webhook_configs is hardcoded as "http://discord-alert:9094/". If this URL might change in the future, consider making it an environment variable.

Won't change in the near future as long as we don't migrate to k8s

> The monitoring/conf/grafana/provisioning/datasources/boostrap.yml file has a typo in its name. It should be bootstrap.yml, not boostrap.yml.

Oh damn, this AI knows what it's doing XD. Will fix

**Review by Lxkas — APPROVED** [review]
boooooo srap

**Pull request merged**
